INSERT INTO `DRINKS`(`NAME`, `TYPE`, `FLAVOR`, `PRICE`) VALUES
    ('Bad Touch',     'Classy', 'Sour',  250.00),
    ('Beer',          'Classic','Bubbly',200.00),
    ('Bleeding Jane', 'Classic','Spicy', 200.00),
    ('Bloom Light',   'Promo',  'Spicy', 230.00),
    ('Blue Fairy',    'Girly',  'Sweet', 170.00),
    ('Brandtini',     'Classy', 'Sweet', 250.00),
    ('Cobalt Velvet', 'Classy', 'Bubbly',280.00),
    ('Crevice Spike', 'Manly',  'Sour',  140.00),
    ('Flaming Moai',  'Classy', 'Spicy', 150.00),
    ('Fluffy Dream',  'Girly',  'Sour',  170.00),
    ('Fringe Weaver', 'Classy', 'Bubbly',260.00),
    ('Frothy Water',  'Classic','Bubbly',150.00),
    ('Grizzly Temple','Promo',  'Bitter',220.00),
    ('Gut Punch',     'Manly',  'Bitter', 80.00),
    ('Marsblast',     'Manly',  'Spicy', 170.00),
    ('Mercuryblast',  'Classy', 'Sour',  250.00),
    ('Moonblast',     'Girly',  'Sweet', 180.00),
    ('Piano Man',     'Promo',  'Sour',  320.00),
    ('Piano Woman',   'Promo',  'Sweet', 320.00),
    ('Pile Driver',   'Manly',  'Bitter',160.00),
    ('Sparkle Star',  'Girly',  'Sweet', 150.00),
    ('Sugar Rush',    'Girly',  'Sweet', 150.00),
    ('Sunshine Cloud','Girly',  'Bitter',150.00),
    ('Suplex',        'Manly',  'Bitter',160.00),
    ('Zen Star',      'Promo',  'Sour',  210.00);